### ISSUE TITLE
Match URLs in a blob of text

### ISSUE THREAD

**Issue by diclophis** [natefaubion/matches.js#1]
Heya,

Could this library be used to extract URLs from a blob of text?

**Comment by natefaubion** [comment]
No, not really. You would want to just use regular expressions for that:
http://www.google.com/search?q=regex+extract+url

This library is meant to inspect the types and structure of the arguments you pass to a function and respond accordingly. It can match on whether a particular argument is of the String type, or whether it matches a particular string literal.
