### ISSUE TITLE
Browser Build

### ISSUE THREAD

**Issue by DamonOehlman** [natefaubion/matches.js#3]
Hey Nate - love what you've created with this library.  I'm not sure if you had any plans to get it working on the browser or not, but I've [forked it](/DamonOehlman/matches.js) and experimented with applying a build process to generate builds that work for CommonJS, AMD and a plain old globbing implementation.

There's still some areas that need attention:
- I need to provide a mechanism for working importing the ADT library in both the CommonJS and browser environments
- Rather than generating specific builds for each environment I need to tweak Interleave to generate a UMDjs variant when no dependencies are required (as is the case with matches.js) - see buildjs/interleave#6

This isn't something I'd open a pull request for as the changes are reasonably significant.  I'd be interested in your thoughts though and whether using a build process to bring matches.js to the browser is something you'd be interested in.  If so, I'm more than happy to help.

Thanks again for a great library.

Cheers,
Damon.

**Comment by DamonOehlman** [comment]
One other thing I should mention also, is that I tweaked the test suite so the tests could be run in the browser as well.  As you used mocha, which is exactly what I use it was pretty simple, but did require moving across to using [expect.js](/Learnboost/expect.js) rather than just plain old assert statements.  If I'm writing a pure node library, I much prefer working with `assert` but as far as I'm aware you need to use something like expect if you want to have tests work in the browser also.

The browser test suite can be found here:

https://github.com/DamonOehlman/matches.js/tree/master/test/browser

**Comment by natefaubion** [comment]
To be honest, I don't know how useful a browser build is at this point. It's a lot of code to include in a page for something that's kind of trivial (to knock my own library). That being said, I've include a bare bones build potentially for demo purposes on a gh-page. I'm not that interested in adding much complexity to get it working universally _for now_. If there appears to be a lot of demand for something more, that can change.

An idea for making it more palatable for browser use might be the ability to precompile the patterns and prepopulate the pattern function cache by passing a newline delimited list of patterns to some cli. That way, the current 500 lines + 3000 lines parser could be reduced to almost nothing. If that interests you, I would make another ticket to work out the details.

**Comment by DamonOehlman** [comment]
@natefaubion Yeah, good point there re the added complexity vs bang for buck in the browser.  I think for the moment I'll be happy to experiment with the simple browser build, and more importantly use the library from within node.  If I get to the point where I'm extremely keen to have it work in the browser in the most efficient way possible, I'll raise that ticket you suggested regarding precompilation.

Cheers,
Damon.
