### ISSUE TITLE
adt.single doesn't work

### ISSUE THREAD

**Issue by ontologiae** [natefaubion/matches.js#8]
In Google Chrome's console :

var Tree = adt.data({
  Empty : adt.single(),
  Node  : adt.record("val", "left", "right")
});

Tree.Empty()

I get : 

TypeError: Property 'Empty' of object function () { if (!(this instanceof D) && D.apply !== funcApply) { return D.apply(this, arguments); } } is not a function

arguments: Array[2]
0: "Empty"
1: function () {
Empty: adt.single.ctr
Node: function () {
**names**: Array[2]
get arguments: function ThrowTypeError() { [native code] }
get caller: function ThrowTypeError() { [native code] }
length: 0
name: ""
prototype: adt.util.inherit.C
seal: function () {
set arguments: function ThrowTypeError() { [native code] }
set caller: function ThrowTypeError() { [native code] }
type: function (name, tmpl) {
**proto**: function Empty() {}
<function scope>
length: 2
**proto**: Array[0]
get message: function () { [native code] }
get stack: function () { [native code] }
set message: function () { [native code] }
set stack: function () { [native code] }
type: "property_not_function"
**proto**: Error

But Tree.Node(12,12,12) works...

**Comment by natefaubion** [comment]
Hi! I think you've uncovered a nice bit of documentation rot. Adt.js actually has its own repo, and the latest stable version over there doesn't require parens to instantiate singles. In this case, `Tree.Empty` is already an instance and doesn't require anything else to be used.
